### ISSUE TITLE
Checking repo... ERROR 'https://git.irs.sh/KNOXDEV/knox-scoop' doesn't look like a valid git repository  Error given: fatal: unable to access 'https://git.irs.sh/KNOXDEV/knox-scoop/': Maximum (20) redirects followed

### ISSUE THREAD

**Issue by SonaliBendre** [KNOXDEV/scoop-backup#16]
add in scoop extras bucket

**Comment by teddue** [comment]
Same problem here

**Comment by KNOXDEV** [comment]
Address this by using using the github bucket mirror (https://github.com/KNOXDEV/knox-scoop) instead of the git.irs.sh bucket. I believe the documentation has all been updated to state this already. 

In any case, I think this project would make a good addition to the scoop-extras bucket, so I'll look into that.
